# Generated by Django 6.0.6 on 2026-06-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_add_resume_embedding_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='source',
            field=models.CharField(choices=[('getajob', 'getajob'), ('upload', 'Upload'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='getajob', max_length=50),
        ),
    ]
